global_frame: map
rolling_window: false
track_unknown_space: false
update_frequency: 1.0
publish_frequency: 1.0

plugins:
  - {name: static_layer,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_layer,               type: "costmap_2d::InflationLayer"}
