footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.03

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.1
use_sim_time: true
rolling_window: false
resolution: 0.05

obstacle_range: 5.5
raytrace_range: 7.0

#layer definitions
static_layer:
  map_topic: /map
  map_subscribe_transient_local: true
  enabled: true
  subscribe_to_updates: true
  transform_tolerance: 0.1

inflation_layer:
  plugin: "nav2_costmap_2d::InflationLayer"
  enabled: true
  inflation_radius: 0.5
  cost_scaling_factor: 5.0
  inflate_unknown: false
  inflate_around_unknown: false
