global_frame: odom
rolling_window: true
update_frequency: 5.0
publish_frequency: 2.0

plugins:
  - {name: normal_layer,                type: "normal_layer_namespace::NormalLayer"}
  - {name: inflation_layer,               type: "costmap_2d::InflationLayer"}
